@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Arial
skinparam defaultFontSize 14
skinparam roundcorner 10
skinparam maxmessagesize 120

actor "GestorDeSeguranca" as Gestor
participant "Módulo Simulação" as UI
participant "Setor" as Setor
participant "SaidaEmergencia" as Saida
participant "ServicoDeRoteamento" as Roteamento
participant "SimulacaoEmergencia" as Simulacao
database "Banco de Dados" as DB

Gestor -> UI : Iniciar Simulação
UI -> Setor : obterDadosPlanta()
Setor -> DB : buscarAreasESaidas()
DB --> Setor : plantaBase
Setor --> UI : carregarMapa

Gestor -> UI : Definir sinistro
UI -> Setor : validarLimitesSetor()
UI -> Setor : bloquearZonaDeImpacto()
Setor -> Saida : definirBloqueio()

UI -> Roteamento : executarBuscaDeCaminho()
Roteamento -> Roteamento : identificarGargalos()

alt Cenário de Exceção I: Sem Saída
  Roteamento -> Roteamento : verificarRotasVezesTotal()
  Roteamento --> UI : erro100PercentBloqueado
  UI --> Gestor : Emite alerta crítico de falha estrutural
else Rotas Encontradas
  Roteamento -> Roteamento : calcularTempoEstimado()
  Roteamento --> UI : rotasAlternativas
  UI --> Gestor : Exibir mapa atualizado
end

opt Cenário Alternativo I: Alteração em Tempo Real
  Gestor -> UI : Bloquear manualmente saída extra
  UI -> Saida : aplicarNovoBloqueio()
  UI -> Roteamento : recalcularRotasTempoReal()
  Roteamento --> UI : novasRotas
  UI --> Gestor : Atualizar projeção instantaneamente
end

Gestor -> UI : Finalizar
UI -> Roteamento : gerarComparativoRealESimulado()
Roteamento -> Simulacao : registrarResultado()
Simulacao -> DB : salvar()
Roteamento --> UI : relatorio
UI --> Gestor : Exibir eficácia
@enduml
