@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Arial
skinparam defaultFontSize 14
skinparam roundcorner 10
skinparam maxmessagesize 120

actor "GestorDeSeguranca" as Gestor
participant "Painel Projeção" as UI
participant "ProjecaoSubstituicao" as Projecao
participant "Emprestimo" as Emprestimo
participant "EPI" as EPI
participant "Estoque" as Estoque
database "Banco de Dados" as DB

== Fluxo Principal (Batch / Automático) ==
UI -> Projecao : gerarAnaliseGeral()
Projecao -> DB : buscarEPIsEmUso()
DB --> Projecao : lista<EPI>

loop Para cada EPI
  Projecao -> Emprestimo : obterHistoricoUsoFrequencia()
  Emprestimo --> Projecao : frequenciaUso
  Projecao -> EPI : verificarValidadeCA()
  
  alt Cenário de Exceção I: CA Expirado em Uso
    EPI -> EPI : CA == vencido && emUso == true
    EPI --> Projecao : riscoLegalDetectado
    Projecao -> UI : notificarFalhaCritica("Substituição imediata e bloqueio de tarefa")
  else CA Válido
    Projecao -> EPI : atualizarPrevisaoDescarte()
  end
end

Projecao -> Estoque : validarCustoHistoricoConsumo()
Estoque -> DB : gerarRequisicaoCompra()
Projecao -> DB : salvarProjecoes()
Projecao --> UI : listaReposição
UI --> Gestor : Exibir itens críticos

== Cenário Alternativo I: Prorrogação ==
opt Aval Técnico Manual
  Gestor -> UI : Realizar inspeção física
  UI -> EPI : inserirAvalTecnico(integridadeOk)
  EPI -> EPI : estenderDataDescarteLimiteCA()
  EPI -> DB : atualizar()
  EPI --> UI : ok
end
@enduml
